version: "2"

run:
  timeout: 5m

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - ineffassign
    - gocritic
  settings:
    errcheck:
      exclude-functions:
        - io.Closer.Close
        - (*database/sql.DB).Close
        - (*database/sql.Rows).Close
        - (*database/sql.Tx).Rollback
        - (*os.File).Close
        - os.Remove
        - (net/http.ResponseWriter).Write
        - (*encoding/json.Encoder).Encode
    gocritic:
      disabled-checks:
        - exitAfterDefer
  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
